# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_name', models.CharField(max_length=50)),
                ('flight_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FlightSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_time', models.DateTimeField()),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.Airline')),
            ],
        ),
    ]
