# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightschedule',
            name='flight_time',
            field=models.CharField(max_length=5),
        ),
    ]
